// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/inventory-reference/InventoryModule.tsx": () => import("../components/mockups/inventory-reference/InventoryModule.tsx")
};
